server:
  port: 8080
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:9296
